server:
  port: 9000

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls[0].name: Account Service
    urls[0].url: /aggregate/account-service/v3/api-docs
    urls[1].name: Fraud Service
    urls[1].url: /aggregate/fraud-service/v3/api-docs
    urls[2].name: Ledger Service
    urls[2].url: /aggregate/ledger-service/v3/api-docs
    urls[3].name: Notification Service
    urls[3].url: /aggregate/notification-service/v3/api-docs
    urls[4].name: Payment Service
    urls[4].url: /aggregate/payment-service/v3/api-docs
    urls[5].name: Wallet Service
    urls[5].url: /aggregate/wallet-service/v3/api-docs

dpal-services:
  account-service: http://localhost:8080
  fraud-service: http://localhost:8084
  ledger-service: http://localhost:8083
  notification-service: http://localhost:8085
  payment-service: http://localhost:8082
  wallet-service: http://localhost:8081