server:
  port: 8080

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3316/account_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.flywaydb: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

wallet:
  url: http://localhost:8081
  connect-timeout: 2s
  read-timeout: 5s